spring.application.name=shopping
spring.datasource.url=jdbc:mysql://localhost:3306/manicart
# ? Connect to "manicart" database in local MySQL server

spring.datasource.username=root
# ? Login using username "root"

spring.datasource.password=manikandan@9500025240
# ? Login using password "root"

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# ? Load MySQL driver to enable connection

spring.jpa.hibernate.ddl-auto=update
# ? Auto create/update tables based on entity classes

spring.jpa.show-sql=true
# ? Display SQL queries in console

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# ? Generate SQL queries in MySQL format

spring.web.resources.static-locations=file:uploads/